# Generated by Django 5.1.4 on 2024-12-16 11:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=2)),
                ('version', models.CharField(max_length=2)),
                ('serial', models.CharField(max_length=5)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RobotModelDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2}$', 'Допустимы только прописные латинские символы и цифры')], verbose_name='Модель робота')),
            ],
        ),
        migrations.CreateModel(
            name='RobotVersionDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2}$', 'Допустимы только прописные латинские символы и цифры')], verbose_name='Версия робота')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='robots.robotmodeldb', verbose_name='Модель робота')),
            ],
        ),
    ]
