# Generated by Django 5.1.4 on 2024-12-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=2)),
                ('version', models.CharField(max_length=2)),
                ('serial', models.CharField(max_length=5)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RobotRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=2)),
                ('version', models.CharField(max_length=2)),
                ('serial', models.CharField(max_length=5)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
